version: '3.8'
services:
  weather-service:
    build: ./weather-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  location-service:
    build: ./location-service
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development

  booking-service:
    build: ./booking-service
    ports:
      - "8085:8085"
    environment:
     - NODE_ENV=development

  room-service:
    build: ./room-service
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=development

  auth-service:
    build: ./auth-service
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=development

  api-gateway:
    build: ./api-gateway
    ports:
      - "8086:8086"
    environment:
      - WEATHER_SERVICE_URL=http://localhost:8080
      - LOCATION_SERVICE_URL=http://localhost:8081
      - BOOKING_SERVICE_URL=http://localhost:8085
      - ROOM_SERVICE_URL=http://localhost:8083
      - AUTH_SERVICE_URL=http://localhost:8084
    depends_on:
      - weather-service
      - location-service
      - room-service 
      - auth-service
      - booking-service
