version: '3.8'
services:
  weather-service:
    build: ./weather-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - LOCATION_SERVICE_URL=http://location-service:8081/api/locations

  location-service:
    build: ./location-service
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - ROOM_SERVICE_URL=http://room-service:8083/api/rooms
      - MONGODB_URL=mongodb+srv://matthewmcc:zVCpwp3W1mmEqNXc@cluster0.lcalcbp.mongodb.net/?appName=Cluster0
      - GEOCODING_URL=https://geocoding-api.open-meteo.com/v1
      - PORT=8081

  booking-service:
    build: ./booking-service
    ports:
      - "8085:8085"
    environment:
     - NODE_ENV=development
     - ROOM_SERVICE_URL=http://room-service:8083/api/rooms
     - WEATHER_SERVICE_URL=http://weather-service:8080/api/weather

  room-service:
    build: ./room-service
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=development

  auth-service:
    build: ./auth-service
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=development

  api-gateway:
    build: ./api-gateway
    ports:
      - "8086:8086"
    environment:
      - WEATHER_SERVICE_URL=http://weather-service:8080
      - LOCATION_SERVICE_URL=http://location-service:8081
      - BOOKING_SERVICE_URL=http://booking-service:8085
      - ROOM_SERVICE_URL=http://room-service:8083
      - AUTH_SERVICE_URL=http://auth-service:8084
    depends_on:
      - weather-service
      - location-service
      - room-service 
      - auth-service
      - booking-service
